#!/bin/bash
# Automatización de pagina web
# Modo de uso: copia o mueve este script a /usr/bin o /usr/local/bin y ejecutarlo de esta manera:
# preins

# Instalar  apache mysql php phpmyadmin coger la base de datos de github e introducira directamente a la base de datos

# Paso 1: Actualizamos el sistema operativo
sudo apt-get update
# Paso 2: Instalar Apache, MySQL, PHP
sudo apt-get install apache2 mysql-client mysql-server php7.0 libapache2-mod-php7.0
# Paso 3: Instalar sofware adicional y necesario
sudo apt-get install graphviz aspell php7.0-pspell php7.0-curl php7.0-gd php7.0-intl php7.0-mysql php7.0-xmlrpc php7.0-ldap php7.0-zip
sudo service apache2 restart
sudo apt-get install git
sudo apt-get install nano
sudo apt-get update
# Paso 4: Crear una base de datos con un usuario
echo 'Introduce el nombre de la base de datos'
read namebd
mysql -u root -p
CREATE DATABASE $namebd;
# Paso 5: Descargar de moodle e instalar BD
cd /opt
sudo git clone https://github.com/davidfc666/Sqlrubrica.git
cd
mysql -u root -p $namebd < /opt/Sqlrubrica/Rubrica2_0.sql
# Paso 6: Instalar PHPMYADMIN - Sin Completar
sudo apt-get install phpmyadmin
cd /etc/apache2
sudo nano apache2.conf
sudo service apache2 restart
# Aqui he añadido una linea:
# include /etc/phpmyadmin/apache.conf

# Paso 7: Introducir programa
exit
sudo service mysql restart
# Paso 6: Descargar la web y la añadimos en var/www/html
sudo chmod -R 777 /var/www/html
cd
cd /var/www/html
sudo git clone https://github.com/Grupo2G2/Reto.git
